trigger:
- refs/heads/master
- refs/heads/dev
pr: ['dev']

variables:
  solution: '**/*.sln'
  testProjects: "**/*Tests/*.csproj"
  publishProject: "**/*Tool/*.csproj"
  buildConfiguration: 'Release'
  major: 4
  minor: 2
  patch: 2
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: Build
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 6 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 7 SDK'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: PowerShell@2
      displayName: 'Build and Test using build.ps1'
      inputs:
        filePath: '$(Build.SourcesDirectory)/build.ps1'
        arguments: '-Framework net8.0 -Configuration $(buildConfiguration) -Clean -Restore -Test'
        workingDirectory: '$(Build.SourcesDirectory)'

    
- stage: Publish_Artifacts
  pool:
      vmImage: 'windows-latest'
      
  jobs:
  - job: Publish
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET 6 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 7 SDK'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 8 SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - task: PowerShell@2
      displayName: 'Build for all frameworks using build.ps1'
      inputs:
        filePath: '$(Build.SourcesDirectory)/build.ps1'
        arguments: '-Framework all -Configuration $(buildConfiguration) -Restore'
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: ComponentGovernanceComponentDetection@0
      condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
      displayName: 'component detection'

    - task: notice@0
      condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
      displayName: 'generate NOTICE file'
      inputs:
        outputformat: 'text'

    - task: DownloadBuildArtifacts@0
      condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'NOTICE.txt'
        downloadPath: '$(Build.SourcesDirectory)/bin/notice'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: 'publish'
        projects: '$(publishProject)'
        arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: false
        zipAfterPublish: True
          
    - task: PowerShell@2
      displayName: 'Pack NuGet packages using build.ps1'
      inputs:
        filePath: '$(Build.SourcesDirectory)/build.ps1'
        arguments: '-Framework all -Configuration $(buildConfiguration) -Pack'
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy NuGet packages to staging'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/packages'
        Contents: '**/*.nupkg'
        TargetFolder: '$(build.artifactStagingDirectory)/nupkgs'

    - task: ManifestGeneratorTask@0
      displayName: 'Generation Task'
      inputs:
        BuildDropPath: '$(build.artifactStagingDirectory)'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'publish binary artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'FhirAnonymizerBuild'
        
    - task: PublishBuildArtifacts@1
      displayName: 'publish nuget artifacts'
      inputs:
        pathtoPublish: '$(build.artifactStagingDirectory)/nupkgs'
        artifactName: 'nuget'
        publishLocation: 'container'

- stage: Release
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Release
    pool:
        vmImage: 'windows-latest'
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifacts'
      inputs:
        artifactName: FhirAnonymizerBuild
        downloadPath: $(System.DefaultWorkingDirectory)

    - task: GithubRelease@1 
      displayName: 'Create GitHub Release'      
      inputs:
        gitHubConnection: microsoft
        repositoryName: microsoft/FHIR-Tools-for-Anonymization
        action: create
        title: v$(major).$(minor).$(patch)
        tagSource: userSpecifiedTag
        tag: v$(major).$(minor).$(patch)    
        assets: |
          $(System.DefaultWorkingDirectory)/FhirAnonymizerBuild/Microsoft.Health.Fhir.Anonymizer.R4.CommandLineTool.zip
          $(System.DefaultWorkingDirectory)/FhirAnonymizerBuild/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.zip
          $(System.DefaultWorkingDirectory)/FhirAnonymizerBuild/Microsoft.Health.Dicom.Anonymizer.CommandLineTool.zip
