#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger:
- refs/heads/master
- refs/heads/dev
pr: ['dev']

parameters: # parameters are shown up in ADO UI in a build queue time
  - name: 'debug'
    displayName: 'Enable debug output'
    type: boolean
    default: false

variables:
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: '5,1000' # Retry nuget restore failures 5 times (this is resolving the "error NU3037: ... The repository primary signature validity period has expired." error during dotnet restore phase)
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  system.debug: ${{ parameters.debug }}
  BuildConfiguration: Release
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2019/vse2022:latest' # Docker image which is used to build the project https://aka.ms/obpipelines/containers

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    featureFlags:
      runHostSDL: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #  enabled: true # SDL results of non-official builds aren't uploaded to TSA by default.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        prerelease: true
        sarif: true
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
        exclusionsFile: $(Build.SourcesDirectory)/PolicheckExclusion.xml
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress
      antimalwareScan:
        enabled: false

    stages:
      - stage: build
        jobs:
          - job: main
            pool:
              type: windows # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs

            variables:
              ob_outputDirectory: '$(Build.SourcesDirectory)\drop' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
              # https://aka.ms/obpipelines/sdl
              ob_sdl_binskim_enabled: false # you can disable sdl tools in non-official build
              # ob_sdl_binskim_break: true # always break the build on binskim issues. You can disable it by setting to 'false'
              # ob_sdl_binskim_scanOutputDirectoryOnly: true
              # ob_sdl_roslyn_break: true
              # ob_sdl_suppression_suppressionFile: $(Build.SourcesDirectory)\.gdn\job.gdnsuppress

            steps:
              - template: .pipelines/templates/Build.yml@self
                parameters:
                  BuildConfiguration: $(BuildConfiguration)
                  EnableOnebranchCodeSigning: false
